name: mowl312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - click
  - deprecated
  - gradle
  - JPype1=1.5.0
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - tqdm
  - urllib3
  - pip
  - pip:
    - gensim>=4.3.0
    - scipy<1.15.0	    
    - pykeen==1.11.0
    - temp
    
