name: mowl311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - click
  - deprecated
  - gensim>=4.3.0
  - gradle
  - JPype1=1.5.0
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - scipy<1.15.0  
  - tqdm
  - urllib3
  - pip
  - pip:
    - pykeen==1.10.2
    - temp
    
