name: mowl39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - deprecated
  - gensim>=4.3.0
  - gradle
  - JPype1=1.4.1
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - scipy  
  - tqdm
  - urllib3
  - pip
  - pip:
    - pykeen>=1.9.1
    - temp
    
